### ISSUE TITLE
empty defaultBlocks in region definition

### ISSUE THREAD

**Issue by mb324-unikent** [unikent/astro#212]
If a region has only one section in it, and that has an empty defaultBlocks definition (which we want sometimes) as per:

```
{
	"name": "content-page--secondary",
	"label": "Generic content page secondary content",
	"version": 1,
	"sections": [
		{
			"name": "secondary",
			"allowedBlocks": [
				"feature-panel--image-v1",
				"feature-panel--video-v1",
				"content-panel--cards-highlight-v1"
			],
			"min": 1,
			"max": 1,
			"optional": true,
			"defaultBlocks": [
			]
		}
	]
}
```

...then the page shows an error with 'there are no sections in this region'.

<img width="1021" alt="screenshot 2017-12-05 11 04 27" src="https://user-images.githubusercontent.com/4171344/33603938-2cdfb0f6-d9ac-11e7-879f-da86cbab4441.png">

However if there are other sections with non-empty defaultBlocks, the empty defaultBlocks doesn't cause an error and everything works fine.

**Comment by samyapp** [comment]
This is happening because the code that "bakes" out a page is only adding regions containing at least one section with a block in it: https://github.com/unikent/astro/blob/08f9bca655b4703881b88f6da287908b5183daf2/app/Models/Page.php#L97

This should instead load the layout definition and loop through the list of defined regions, adding an empty one (with empty sections) if it does not exist.
